// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(matrix_cryptoFFI)
import matrix_cryptoFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_matrix_crypto_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_matrix_crypto_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureMatrixCryptoCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol MatrixCryptoProtocol: AnyObject, Sendable {
    
    func addDevice(device: DeviceInfo) throws 
    
    func cancelVerification(verificationId: String) throws 
    
    func completeVerification(verificationId: String) throws 
    
    func confirmSas(verificationId: String) throws 
    
    func decryptEvent(roomId: String, encryptedContent: String) throws  -> String
    
    func deviceFingerprint()  -> String
    
    func deviceId()  -> String
    
    func enableRoomEncryption(roomId: String, algorithm: String) throws 
    
    func encryptEvent(roomId: String, eventType: String, content: String) throws  -> String
    
    func getRoomEncryptionState(roomId: String) throws  -> RoomEncryptionState
    
    func getSasEmojis(verificationId: String) throws  -> [EmojiSasPair]
    
    func getUserDevices(userId: String) throws  -> [DeviceInfo]
    
    func getVerificationState(verificationId: String) throws  -> VerificationState
    
    func startVerification(otherUserId: String, otherDeviceId: String) throws  -> VerificationState
    
    func userId()  -> String
    
}
open class MatrixCrypto: MatrixCryptoProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_matrix_crypto_core_fn_clone_matrixcrypto(self.handle, $0) }
    }
public convenience init(userId: String, deviceId: String, pickleKey: String)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_matrix_crypto_core_fn_constructor_matrixcrypto_new(
        FfiConverterString.lower(userId),
        FfiConverterString.lower(deviceId),
        FfiConverterString.lower(pickleKey),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_matrix_crypto_core_fn_free_matrixcrypto(handle, $0) }
    }

    

    
open func addDevice(device: DeviceInfo)throws   {try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_matrix_crypto_core_fn_method_matrixcrypto_add_device(
            self.uniffiCloneHandle(),
        FfiConverterTypeDeviceInfo_lower(device),$0
    )
}
}
    
open func cancelVerification(verificationId: String)throws   {try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_matrix_crypto_core_fn_method_matrixcrypto_cancel_verification(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(verificationId),$0
    )
}
}
    
open func completeVerification(verificationId: String)throws   {try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_matrix_crypto_core_fn_method_matrixcrypto_complete_verification(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(verificationId),$0
    )
}
}
    
open func confirmSas(verificationId: String)throws   {try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_matrix_crypto_core_fn_method_matrixcrypto_confirm_sas(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(verificationId),$0
    )
}
}
    
open func decryptEvent(roomId: String, encryptedContent: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_matrix_crypto_core_fn_method_matrixcrypto_decrypt_event(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(roomId),
        FfiConverterString.lower(encryptedContent),$0
    )
})
}
    
open func deviceFingerprint() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_matrix_crypto_core_fn_method_matrixcrypto_device_fingerprint(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func deviceId() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_matrix_crypto_core_fn_method_matrixcrypto_device_id(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func enableRoomEncryption(roomId: String, algorithm: String)throws   {try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_matrix_crypto_core_fn_method_matrixcrypto_enable_room_encryption(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(roomId),
        FfiConverterString.lower(algorithm),$0
    )
}
}
    
open func encryptEvent(roomId: String, eventType: String, content: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_matrix_crypto_core_fn_method_matrixcrypto_encrypt_event(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(roomId),
        FfiConverterString.lower(eventType),
        FfiConverterString.lower(content),$0
    )
})
}
    
open func getRoomEncryptionState(roomId: String)throws  -> RoomEncryptionState  {
    return try  FfiConverterTypeRoomEncryptionState_lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_matrix_crypto_core_fn_method_matrixcrypto_get_room_encryption_state(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(roomId),$0
    )
})
}
    
open func getSasEmojis(verificationId: String)throws  -> [EmojiSasPair]  {
    return try  FfiConverterSequenceTypeEmojiSASPair.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_matrix_crypto_core_fn_method_matrixcrypto_get_sas_emojis(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(verificationId),$0
    )
})
}
    
open func getUserDevices(userId: String)throws  -> [DeviceInfo]  {
    return try  FfiConverterSequenceTypeDeviceInfo.lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_matrix_crypto_core_fn_method_matrixcrypto_get_user_devices(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(userId),$0
    )
})
}
    
open func getVerificationState(verificationId: String)throws  -> VerificationState  {
    return try  FfiConverterTypeVerificationState_lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_matrix_crypto_core_fn_method_matrixcrypto_get_verification_state(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(verificationId),$0
    )
})
}
    
open func startVerification(otherUserId: String, otherDeviceId: String)throws  -> VerificationState  {
    return try  FfiConverterTypeVerificationState_lift(try rustCallWithError(FfiConverterTypeCryptoError_lift) {
    uniffi_matrix_crypto_core_fn_method_matrixcrypto_start_verification(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(otherUserId),
        FfiConverterString.lower(otherDeviceId),$0
    )
})
}
    
open func userId() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_matrix_crypto_core_fn_method_matrixcrypto_user_id(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMatrixCrypto: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = MatrixCrypto

    public static func lift(_ handle: UInt64) throws -> MatrixCrypto {
        return MatrixCrypto(unsafeFromHandle: handle)
    }

    public static func lower(_ value: MatrixCrypto) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MatrixCrypto {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: MatrixCrypto, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMatrixCrypto_lift(_ handle: UInt64) throws -> MatrixCrypto {
    return try FfiConverterTypeMatrixCrypto.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMatrixCrypto_lower(_ value: MatrixCrypto) -> UInt64 {
    return FfiConverterTypeMatrixCrypto.lower(value)
}




public struct DeviceInfo: Equatable, Hashable {
    public var deviceId: String
    public var userId: String
    public var displayName: String?
    public var fingerprint: String
    public var isVerified: Bool
    public var isBlocked: Bool
    public var algorithm: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(deviceId: String, userId: String, displayName: String?, fingerprint: String, isVerified: Bool, isBlocked: Bool, algorithm: String) {
        self.deviceId = deviceId
        self.userId = userId
        self.displayName = displayName
        self.fingerprint = fingerprint
        self.isVerified = isVerified
        self.isBlocked = isBlocked
        self.algorithm = algorithm
    }

    

    
}

#if compiler(>=6)
extension DeviceInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDeviceInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DeviceInfo {
        return
            try DeviceInfo(
                deviceId: FfiConverterString.read(from: &buf), 
                userId: FfiConverterString.read(from: &buf), 
                displayName: FfiConverterOptionString.read(from: &buf), 
                fingerprint: FfiConverterString.read(from: &buf), 
                isVerified: FfiConverterBool.read(from: &buf), 
                isBlocked: FfiConverterBool.read(from: &buf), 
                algorithm: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: DeviceInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.deviceId, into: &buf)
        FfiConverterString.write(value.userId, into: &buf)
        FfiConverterOptionString.write(value.displayName, into: &buf)
        FfiConverterString.write(value.fingerprint, into: &buf)
        FfiConverterBool.write(value.isVerified, into: &buf)
        FfiConverterBool.write(value.isBlocked, into: &buf)
        FfiConverterString.write(value.algorithm, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDeviceInfo_lift(_ buf: RustBuffer) throws -> DeviceInfo {
    return try FfiConverterTypeDeviceInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDeviceInfo_lower(_ value: DeviceInfo) -> RustBuffer {
    return FfiConverterTypeDeviceInfo.lower(value)
}


public struct EmojiSasPair: Equatable, Hashable {
    public var emoji: String
    public var name: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(emoji: String, name: String) {
        self.emoji = emoji
        self.name = name
    }

    

    
}

#if compiler(>=6)
extension EmojiSasPair: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEmojiSASPair: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EmojiSasPair {
        return
            try EmojiSasPair(
                emoji: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: EmojiSasPair, into buf: inout [UInt8]) {
        FfiConverterString.write(value.emoji, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEmojiSASPair_lift(_ buf: RustBuffer) throws -> EmojiSasPair {
    return try FfiConverterTypeEmojiSASPair.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEmojiSASPair_lower(_ value: EmojiSasPair) -> RustBuffer {
    return FfiConverterTypeEmojiSASPair.lower(value)
}


public struct EncryptionAlgorithm: Equatable, Hashable {
    public var algorithm: String
    public var rotationPeriodMs: UInt64
    public var rotationPeriodMsgs: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(algorithm: String, rotationPeriodMs: UInt64, rotationPeriodMsgs: UInt64) {
        self.algorithm = algorithm
        self.rotationPeriodMs = rotationPeriodMs
        self.rotationPeriodMsgs = rotationPeriodMsgs
    }

    

    
}

#if compiler(>=6)
extension EncryptionAlgorithm: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEncryptionAlgorithm: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EncryptionAlgorithm {
        return
            try EncryptionAlgorithm(
                algorithm: FfiConverterString.read(from: &buf), 
                rotationPeriodMs: FfiConverterUInt64.read(from: &buf), 
                rotationPeriodMsgs: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: EncryptionAlgorithm, into buf: inout [UInt8]) {
        FfiConverterString.write(value.algorithm, into: &buf)
        FfiConverterUInt64.write(value.rotationPeriodMs, into: &buf)
        FfiConverterUInt64.write(value.rotationPeriodMsgs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptionAlgorithm_lift(_ buf: RustBuffer) throws -> EncryptionAlgorithm {
    return try FfiConverterTypeEncryptionAlgorithm.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptionAlgorithm_lower(_ value: EncryptionAlgorithm) -> RustBuffer {
    return FfiConverterTypeEncryptionAlgorithm.lower(value)
}


public struct RoomEncryptionState: Equatable, Hashable {
    public var roomId: String
    public var isEncrypted: Bool
    public var algorithm: String?
    public var trustedDevices: [String]
    public var untrustedDevices: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(roomId: String, isEncrypted: Bool, algorithm: String?, trustedDevices: [String], untrustedDevices: [String]) {
        self.roomId = roomId
        self.isEncrypted = isEncrypted
        self.algorithm = algorithm
        self.trustedDevices = trustedDevices
        self.untrustedDevices = untrustedDevices
    }

    

    
}

#if compiler(>=6)
extension RoomEncryptionState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRoomEncryptionState: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RoomEncryptionState {
        return
            try RoomEncryptionState(
                roomId: FfiConverterString.read(from: &buf), 
                isEncrypted: FfiConverterBool.read(from: &buf), 
                algorithm: FfiConverterOptionString.read(from: &buf), 
                trustedDevices: FfiConverterSequenceString.read(from: &buf), 
                untrustedDevices: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: RoomEncryptionState, into buf: inout [UInt8]) {
        FfiConverterString.write(value.roomId, into: &buf)
        FfiConverterBool.write(value.isEncrypted, into: &buf)
        FfiConverterOptionString.write(value.algorithm, into: &buf)
        FfiConverterSequenceString.write(value.trustedDevices, into: &buf)
        FfiConverterSequenceString.write(value.untrustedDevices, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRoomEncryptionState_lift(_ buf: RustBuffer) throws -> RoomEncryptionState {
    return try FfiConverterTypeRoomEncryptionState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRoomEncryptionState_lower(_ value: RoomEncryptionState) -> RustBuffer {
    return FfiConverterTypeRoomEncryptionState.lower(value)
}


public struct UserDevices: Equatable, Hashable {
    public var userId: String
    public var devices: [DeviceInfo]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(userId: String, devices: [DeviceInfo]) {
        self.userId = userId
        self.devices = devices
    }

    

    
}

#if compiler(>=6)
extension UserDevices: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeUserDevices: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UserDevices {
        return
            try UserDevices(
                userId: FfiConverterString.read(from: &buf), 
                devices: FfiConverterSequenceTypeDeviceInfo.read(from: &buf)
        )
    }

    public static func write(_ value: UserDevices, into buf: inout [UInt8]) {
        FfiConverterString.write(value.userId, into: &buf)
        FfiConverterSequenceTypeDeviceInfo.write(value.devices, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUserDevices_lift(_ buf: RustBuffer) throws -> UserDevices {
    return try FfiConverterTypeUserDevices.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeUserDevices_lower(_ value: UserDevices) -> RustBuffer {
    return FfiConverterTypeUserDevices.lower(value)
}


public struct VerificationState: Equatable, Hashable {
    public var verificationId: String
    public var state: String
    public var otherUserId: String
    public var otherDeviceId: String
    public var emojis: [EmojiSasPair]
    public var decimals: [UInt32]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(verificationId: String, state: String, otherUserId: String, otherDeviceId: String, emojis: [EmojiSasPair], decimals: [UInt32]) {
        self.verificationId = verificationId
        self.state = state
        self.otherUserId = otherUserId
        self.otherDeviceId = otherDeviceId
        self.emojis = emojis
        self.decimals = decimals
    }

    

    
}

#if compiler(>=6)
extension VerificationState: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVerificationState: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VerificationState {
        return
            try VerificationState(
                verificationId: FfiConverterString.read(from: &buf), 
                state: FfiConverterString.read(from: &buf), 
                otherUserId: FfiConverterString.read(from: &buf), 
                otherDeviceId: FfiConverterString.read(from: &buf), 
                emojis: FfiConverterSequenceTypeEmojiSASPair.read(from: &buf), 
                decimals: FfiConverterSequenceUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: VerificationState, into buf: inout [UInt8]) {
        FfiConverterString.write(value.verificationId, into: &buf)
        FfiConverterString.write(value.state, into: &buf)
        FfiConverterString.write(value.otherUserId, into: &buf)
        FfiConverterString.write(value.otherDeviceId, into: &buf)
        FfiConverterSequenceTypeEmojiSASPair.write(value.emojis, into: &buf)
        FfiConverterSequenceUInt32.write(value.decimals, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVerificationState_lift(_ buf: RustBuffer) throws -> VerificationState {
    return try FfiConverterTypeVerificationState.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVerificationState_lower(_ value: VerificationState) -> RustBuffer {
    return FfiConverterTypeVerificationState.lower(value)
}


public enum CryptoError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case InitializationFailed(message: String)
    
    case EncryptionFailed(message: String)
    
    case DecryptionFailed(message: String)
    
    case VerificationFailed(message: String)
    
    case StorageError(message: String)
    
    case InvalidUserId(message: String)
    
    case InvalidDeviceId(message: String)
    
    case DeviceNotFound(message: String)
    
    case VerificationNotFound(message: String)
    
    case InvalidState(message: String)
    
    case NetworkError(message: String)
    
    case Unknown(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension CryptoError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCryptoError: FfiConverterRustBuffer {
    typealias SwiftType = CryptoError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CryptoError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InitializationFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .EncryptionFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .DecryptionFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .VerificationFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .StorageError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .InvalidUserId(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .InvalidDeviceId(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 8: return .DeviceNotFound(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 9: return .VerificationNotFound(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 10: return .InvalidState(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 11: return .NetworkError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 12: return .Unknown(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CryptoError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .InitializationFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .EncryptionFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .DecryptionFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .VerificationFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .StorageError(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .InvalidUserId(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))
        case .InvalidDeviceId(_ /* message is ignored*/):
            writeInt(&buf, Int32(7))
        case .DeviceNotFound(_ /* message is ignored*/):
            writeInt(&buf, Int32(8))
        case .VerificationNotFound(_ /* message is ignored*/):
            writeInt(&buf, Int32(9))
        case .InvalidState(_ /* message is ignored*/):
            writeInt(&buf, Int32(10))
        case .NetworkError(_ /* message is ignored*/):
            writeInt(&buf, Int32(11))
        case .Unknown(_ /* message is ignored*/):
            writeInt(&buf, Int32(12))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCryptoError_lift(_ buf: RustBuffer) throws -> CryptoError {
    return try FfiConverterTypeCryptoError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCryptoError_lower(_ value: CryptoError) -> RustBuffer {
    return FfiConverterTypeCryptoError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt32: FfiConverterRustBuffer {
    typealias SwiftType = [UInt32]

    public static func write(_ value: [UInt32], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt32.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt32] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt32]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt32.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDeviceInfo: FfiConverterRustBuffer {
    typealias SwiftType = [DeviceInfo]

    public static func write(_ value: [DeviceInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDeviceInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DeviceInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [DeviceInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDeviceInfo.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeEmojiSASPair: FfiConverterRustBuffer {
    typealias SwiftType = [EmojiSasPair]

    public static func write(_ value: [EmojiSasPair], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeEmojiSASPair.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [EmojiSasPair] {
        let len: Int32 = try readInt(&buf)
        var seq = [EmojiSasPair]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeEmojiSASPair.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_matrix_crypto_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_matrix_crypto_core_checksum_method_matrixcrypto_add_device() != 7416) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_matrix_crypto_core_checksum_method_matrixcrypto_cancel_verification() != 60694) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_matrix_crypto_core_checksum_method_matrixcrypto_complete_verification() != 16445) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_matrix_crypto_core_checksum_method_matrixcrypto_confirm_sas() != 19640) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_matrix_crypto_core_checksum_method_matrixcrypto_decrypt_event() != 29667) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_matrix_crypto_core_checksum_method_matrixcrypto_device_fingerprint() != 22956) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_matrix_crypto_core_checksum_method_matrixcrypto_device_id() != 59366) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_matrix_crypto_core_checksum_method_matrixcrypto_enable_room_encryption() != 19156) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_matrix_crypto_core_checksum_method_matrixcrypto_encrypt_event() != 32786) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_matrix_crypto_core_checksum_method_matrixcrypto_get_room_encryption_state() != 53908) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_matrix_crypto_core_checksum_method_matrixcrypto_get_sas_emojis() != 30646) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_matrix_crypto_core_checksum_method_matrixcrypto_get_user_devices() != 53426) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_matrix_crypto_core_checksum_method_matrixcrypto_get_verification_state() != 8793) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_matrix_crypto_core_checksum_method_matrixcrypto_start_verification() != 42482) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_matrix_crypto_core_checksum_method_matrixcrypto_user_id() != 51351) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_matrix_crypto_core_checksum_constructor_matrixcrypto_new() != 14807) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureMatrixCryptoCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all