// MatrixCryptoBridge.swift
// Thin Swift wrapper around the UniFFI-generated MatrixCrypto class.
// The real types (MatrixCrypto, DeviceInfo, VerificationState, etc.) come from
// matrix_crypto.swift which is generated by uniffi-bindgen from matrix_crypto.udl.

import Foundation

/// Singleton bridge that holds the live MatrixCrypto instance.
@objc public class MatrixCryptoBridge: NSObject {

    private static var instance: MatrixCrypto?

    // MARK: - Lifecycle

    @objc public static func initialize(
        userId: String,
        deviceId: String,
        pickleKey: String
    ) throws {
        instance = try MatrixCrypto(
            userId: userId,
            deviceId: deviceId,
            pickleKey: pickleKey
        )
    }

    @objc public static func destroy() {
        instance = nil
    }

    // MARK: - Device Information

    @objc public static func getDeviceFingerprint() throws -> String {
        return try requireInstance().deviceFingerprint()
    }

    @objc public static func getUserId() throws -> String {
        return try requireInstance().userId()
    }

    @objc public static func getDeviceId() throws -> String {
        return try requireInstance().deviceId()
    }

    // MARK: - Device Management

    @objc public static func getUserDevices(userId: String) throws -> [[String: Any]] {
        let devices = try requireInstance().getUserDevices(userId: userId)
        return devices.map { deviceInfoToDict($0) }
    }

    @objc public static func addDevice(device: [String: Any]) throws {
        let info = dictToDeviceInfo(device)
        try requireInstance().addDevice(device: info)
    }

    // MARK: - Device Verification

    @objc public static func startVerification(
        otherUserId: String,
        otherDeviceId: String
    ) throws -> [String: Any] {
        let state = try requireInstance().startVerification(
            otherUserId: otherUserId,
            otherDeviceId: otherDeviceId
        )
        return verificationStateToDict(state)
    }

    @objc public static func getSasEmojis(verificationId: String) throws -> [[String: String]] {
        let emojis = try requireInstance().getSasEmojis(verificationId: verificationId)
        return emojis.map { ["emoji": $0.emoji, "name": $0.name] }
    }

    @objc public static func confirmSas(verificationId: String) throws {
        try requireInstance().confirmSas(verificationId: verificationId)
    }

    @objc public static func completeVerification(verificationId: String) throws {
        try requireInstance().completeVerification(verificationId: verificationId)
    }

    @objc public static func cancelVerification(verificationId: String) throws {
        try requireInstance().cancelVerification(verificationId: verificationId)
    }

    @objc public static func getVerificationState(verificationId: String) throws -> [String: Any] {
        let state = try requireInstance().getVerificationState(verificationId: verificationId)
        return verificationStateToDict(state)
    }

    // MARK: - Room Encryption

    @objc public static func enableRoomEncryption(roomId: String, algorithm: String) throws {
        try requireInstance().enableRoomEncryption(roomId: roomId, algorithm: algorithm)
    }

    @objc public static func getRoomEncryptionState(roomId: String) throws -> [String: Any] {
        let state = try requireInstance().getRoomEncryptionState(roomId: roomId)
        return [
            "roomId": state.roomId,
            "isEncrypted": state.isEncrypted,
            "algorithm": state.algorithm as Any,
            "trustedDevices": state.trustedDevices,
            "untrustedDevices": state.untrustedDevices
        ]
    }

    // MARK: - Event Encryption/Decryption

    @objc public static func encryptEvent(
        roomId: String,
        eventType: String,
        content: String
    ) throws -> String {
        return try requireInstance().encryptEvent(
            roomId: roomId,
            eventType: eventType,
            content: content
        )
    }

    @objc public static func decryptEvent(
        roomId: String,
        encryptedContent: String
    ) throws -> String {
        return try requireInstance().decryptEvent(
            roomId: roomId,
            encryptedContent: encryptedContent
        )
    }

    // MARK: - Key Exchange (T1-1: Olm key sharing)

    @objc public static func getIdentityKey() throws -> String {
        return try requireInstance().getIdentityKey()
    }

    @objc public static func getOutboundSessionKey(roomId: String) throws -> String {
        return try requireInstance().getOutboundSessionKey(roomId: roomId)
    }

    @objc public static func getOutboundSessionId(roomId: String) throws -> String {
        return try requireInstance().getOutboundSessionId(roomId: roomId)
    }

    @objc public static func addInboundSession(
        roomId: String,
        senderKey: String,
        sessionKeyBase64: String
    ) throws {
        try requireInstance().addInboundSession(
            roomId: roomId,
            senderKey: senderKey,
            sessionKeyBase64: sessionKeyBase64
        )
    }

    @objc public static func importInboundSession(
        roomId: String,
        senderKey: String,
        exportedKeyBase64: String
    ) throws {
        try requireInstance().importInboundSession(
            roomId: roomId,
            senderKey: senderKey,
            exportedKeyBase64: exportedKeyBase64
        )
    }

    @objc public static func createOlmSession(
        userId: String,
        deviceId: String,
        theirIdentityKey: String,
        theirOneTimeKey: String
    ) throws {
        try requireInstance().createOlmSession(
            userId: userId,
            deviceId: deviceId,
            theirIdentityKey: theirIdentityKey,
            theirOneTimeKey: theirOneTimeKey
        )
    }

    @objc public static func olmEncrypt(
        userId: String,
        deviceId: String,
        plaintext: String
    ) throws -> String {
        return try requireInstance().olmEncrypt(
            userId: userId,
            deviceId: deviceId,
            plaintext: plaintext
        )
    }

    @objc public static func olmDecrypt(
        senderIdentityKey: String,
        msgType: UInt32,
        ciphertextB64: String
    ) throws -> String {
        return try requireInstance().olmDecrypt(
            senderIdentityKey: senderIdentityKey,
            msgType: msgType,
            ciphertextB64: ciphertextB64
        )
    }

    // MARK: - Key Upload (T1-1: device keys + one-time keys)

    @objc public static func getDeviceKeysJson() throws -> String {
        return try requireInstance().getDeviceKeysJson()
    }

    @objc public static func generateOneTimeKeysJson(count: UInt32) throws -> String {
        return try requireInstance().generateOneTimeKeysJson(count: count)
    }

    @objc public static func markKeysAsPublished() throws {
        try requireInstance().markKeysAsPublished()
    }

    // MARK: - State Persistence

    @objc public static func exportState() throws -> String {
        return try requireInstance().exportState()
    }

    @objc public static func importState(stateJson: String) throws -> NSNumber {
        let result = try requireInstance().importState(stateJson: stateJson)
        return NSNumber(value: result)
    }

    // MARK: - Private Helpers

    private static func requireInstance() throws -> MatrixCrypto {
        guard let inst = instance else {
            throw NSError(
                domain: "MatrixCryptoBridge",
                code: -1,
                userInfo: [NSLocalizedDescriptionKey: "MatrixCrypto not initialized. Call initialize() first."]
            )
        }
        return inst
    }

    private static func deviceInfoToDict(_ d: DeviceInfo) -> [String: Any] {
        return [
            "deviceId": d.deviceId,
            "userId": d.userId,
            "displayName": d.displayName as Any,
            "fingerprint": d.fingerprint,
            "isVerified": d.isVerified,
            "isBlocked": d.isBlocked,
            "algorithm": d.algorithm
        ]
    }

    private static func dictToDeviceInfo(_ d: [String: Any]) -> DeviceInfo {
        return DeviceInfo(
            deviceId: d["deviceId"] as? String ?? "",
            userId: d["userId"] as? String ?? "",
            displayName: d["displayName"] as? String,
            fingerprint: d["fingerprint"] as? String ?? "",
            isVerified: d["isVerified"] as? Bool ?? false,
            isBlocked: d["isBlocked"] as? Bool ?? false,
            algorithm: d["algorithm"] as? String ?? "m.olm.v1.curve25519-aes-sha2"
        )
    }

    private static func verificationStateToDict(_ s: VerificationState) -> [String: Any] {
        return [
            "verificationId": s.verificationId,
            "state": s.state,
            "otherUserId": s.otherUserId,
            "otherDeviceId": s.otherDeviceId,
            "emojis": s.emojis.map { ["emoji": $0.emoji, "name": $0.name] },
            "decimals": s.decimals
        ]
    }
}
