/**
 * RNMatrixCryptoTurboModule.mm
 *
 * Adds RCTTurboModule conformance to the RNMatrixCrypto Swift class so that
 * React Native's New Architecture routes method calls through ObjCTurboModule
 * (JSI-based) instead of ObjCInteropTurboModule (which crashes on zero-real-arg
 * promise methods like getDeviceFingerprint).
 *
 * Why not #ifdef RCT_NEW_ARCH_ENABLED?
 *   That flag is placed in OTHER_CPLUSPLUSFLAGS on the Fortress APP target's
 *   xcconfig (Pods-Fortress.debug.xcconfig), NOT on the individual pod target
 *   xcconfig (react-native-matrix-crypto.debug.xcconfig). The pod compiles in
 *   a separate Xcode target that only inherits from the Pods project settings,
 *   so RCT_NEW_ARCH_ENABLED is undefined during pod compilation and the guard
 *   silently empties the file.
 *
 * Solution: use __has_include as the sole guard.
 *   - New Architecture: codegen ran, spec header exists → category compiled.
 *   - Old Architecture: no spec header → __has_include is false → empty file.
 *
 * The spec header is accessible to the pod because the pod xcconfig includes
 * "${PODS_ROOT}/Headers/Public" in HEADER_SEARCH_PATHS, which is the parent
 * directory of ReactCodegen/RNMatrixCryptoSpec/RNMatrixCryptoSpec.h.
 */

#import <Foundation/Foundation.h>

// Expose the Swift-defined RNMatrixCrypto class to this ObjC++ translation
// unit. CocoaPods generates this header for every mixed-language pod; the name
// is the module name (pod name with dashes replaced by underscores) + "-Swift.h".
// Without this import the compiler can't see the @interface for RNMatrixCrypto
// and the category declarations below fail with
//   "cannot find interface declaration for 'RNMatrixCrypto'"
#import "react_native_matrix_crypto-Swift.h"

// Resolve spec header — try Expo/RN 0.73+ path first, then bare RN CLI path.
#if __has_include(<ReactCodegen/RNMatrixCryptoSpec/RNMatrixCryptoSpec.h>)
  #import <ReactCodegen/RNMatrixCryptoSpec/RNMatrixCryptoSpec.h>
  #define RN_MATRIX_CRYPTO_SPEC_FOUND 1
#elif __has_include(<RNMatrixCryptoSpec/RNMatrixCryptoSpec.h>)
  #import <RNMatrixCryptoSpec/RNMatrixCryptoSpec.h>
  #define RN_MATRIX_CRYPTO_SPEC_FOUND 1
#endif

#ifdef RN_MATRIX_CRYPTO_SPEC_FOUND

using namespace facebook::react;

/**
 * Extend RNMatrixCrypto with NativeMatrixCryptoSpec conformance via an ObjC
 * category. NativeMatrixCryptoSpec extends RCTTurboModule, so after this
 * category is loaded, [module conformsToProtocol:@protocol(RCTTurboModule)]
 * returns YES and RCTTurboModuleManager selects ObjCTurboModule instead of
 * ObjCInteropTurboModule.
 */
@interface RNMatrixCrypto (TurboModule) <NativeMatrixCryptoSpec>
@end

@implementation RNMatrixCrypto (TurboModule)

/**
 * Return a NativeMatrixCryptoSpecJSI (generated by codegen) which has the
 * full methodMap_ pre-populated. ObjCTurboModule::invokeObjCMethod uses this
 * map to call each @objc selector with PromiseKind — resolve/reject are
 * handled entirely through JSI and never pass through setInvocationArg.
 */
- (std::shared_ptr<TurboModule>)getTurboModule:(const ObjCTurboModule::InitParams &)params {
  return std::make_shared<NativeMatrixCryptoSpecJSI>(params);
}

@end

#endif  // RN_MATRIX_CRYPTO_SPEC_FOUND
