/**
 * RNMatrixCryptoTurboModule.mm
 *
 * Adds RCTTurboModule conformance to the RNMatrixCrypto Swift class so that
 * React Native's New Architecture routes method calls through ObjCTurboModule
 * (JSI-based, handles RCTPromiseResolveBlock correctly) instead of
 * ObjCInteropTurboModule (which crashes on promise block arguments).
 *
 * How it works:
 *   RCTTurboModuleManager checks `-conformsToProtocol:@protocol(RCTTurboModule)`
 *   at module-lookup time. When it returns YES, the module is instantiated as an
 *   ObjCTurboModule (or subclass) and method calls go through
 *   ObjCTurboModule::invokeObjCMethod, which resolves promises via JSI and never
 *   calls setInvocationArg with a promise block type.
 *
 *   Without this file the Swift class only conforms to NSObject + RCTBridgeModule
 *   (added by RCT_EXTERN_MODULE), so it falls through to ObjCInteropTurboModule
 *   and crashes on any method whose first declared parameter is a promise block.
 *
 * This file must be compiled as Obj-C++ (.mm) because the TurboModule spec uses
 * C++ std::shared_ptr.  It is guarded by RCT_NEW_ARCH_ENABLED so it compiles
 * away cleanly when the old bridge is in use.
 */

#ifdef RCT_NEW_ARCH_ENABLED

#import <Foundation/Foundation.h>

// The spec header is generated by expo prebuild / react-native codegen from the
// codegenConfig in package.json. CocoaPods adds the generated directory to the
// pod's HEADER_SEARCH_PATHS, so the angle-bracket import resolves at build time.
#if __has_include(<RNMatrixCryptoSpec/RNMatrixCryptoSpec.h>)
#import <RNMatrixCryptoSpec/RNMatrixCryptoSpec.h>

using namespace facebook::react;

// Add NativeMatrixCryptoSpec (which extends RCTTurboModule) to the existing
// RNMatrixCrypto class via an Obj-C category.  The category satisfies
// conformsToProtocol:@protocol(RCTTurboModule) at runtime.
@interface RNMatrixCrypto (TurboModule) <NativeMatrixCryptoSpec>
@end

@implementation RNMatrixCrypto (TurboModule)

/**
 * Returns a NativeMatrixCryptoSpecJSI instance which has the full methodMap_
 * populated by codegen.  ObjCTurboModule::invokeObjCMethod then forwards each
 * call to the matching @objc selector on this Swift class using PromiseKind,
 * so promise resolve/reject are handled entirely through JSI — never through
 * setInvocationArg.
 */
- (std::shared_ptr<TurboModule>)getTurboModule:(const ObjCTurboModule::InitParams &)params {
  return std::make_shared<NativeMatrixCryptoSpecJSI>(params);
}

@end

#endif // __has_include
#endif // RCT_NEW_ARCH_ENABLED
